Feature: Pull metadata UIDs from instance
EyeSeeTea/metadata-generator-script pull request #9
Opened 2022-07-08 10:21 UTC by nshandra

DESCRIPTION
Task link: https://app.clickup.com/t/2ew2g7y

Adds the ability to retrieve the IDs for metadata present in a Google spreadsheet from a DHIS2 instance.
The metadata present in the spreadsheet acts as a filter.

IMPLEMENTATION
This script makes sure that two elements can not have the same name, which is possible in a DHIS2 instance.
Its possible to specify a path for the CSV files with the PULL_METADATA_CSV_PATH env var.

2022-07-19 09:42 UTC, jordibc requested changes
Thanks @nshandra !

Let me mention a few issues other than the other comments:

* The files are not prettified (yarn prettify). Having vscode with extension Prettier + setting "Format on save" enabled is an easy way to do it.
* The code in download-ids.ts and upload-server.ts has a few things in common (including `loadSheet()` and `makeSeed()`. I think those could move to a separate file (in `utils/` for example) that they both use.

2022-10-19 18:01 UTC, nshandra commented on README.md
> +After that, you can run `yarn update-server` to generate and update the metadata
Changed to build-metadata.ts

2022-10-19 18:19 UTC, nshandra commented on README.md
> +
Updated for clarity.

2022-10-19 18:23 UTC, nshandra commented on package.json
> +        "build": "ncc build src/scripts/upload-server.ts -m && cp dist/index.js $npm_package_name.js",
Build command removed from `package.json`.

2022-10-19 18:25 UTC, nshandra commented on src/utils/pullMetadata.ts
> +import { createObjectCsvWriter } from "csv-writer";
Added `csv-writer` package to `package.json`.

2022-10-19 18:33 UTC, nshandra commented on src/scripts/download-ids.ts
> +async function download_ids() {
Fixed it. Prettified `download-ids.ts` and `pullMetadata.ts`.

2022-10-20 18:39 UTC, nshandra commented
After looking into it i have removed `programRuleActions` from `allowedTypesArray` by now.
First, because it lacks a name-like field, but also because it can store a lot of different actions (potentially of the same kind) so we would need to make a comparison of multiple fields and get the programRule Id.

Not sure if this merits the extra work, will bring it up to Nacho tomorrow.

2022-10-27 11:24 UTC, nshandra commented
Add programRuleActions back, and fixed the unused name field in programRuleActions, its now the programRuleActionType field.

2023-08-30 13:05 UTC, merged